name: Build and Push Docker Image
permissions: {}
on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        required: true
        description: Docker image name
        options:
        - build-android-rust
        - build-linux-rust
        - build-windows-rust
        - package-aar
      rust_version:
        type: string
        required: true
        description: Version of Rust base image
      version:
        type: string
        required: true
        description: Output Docker image version

env:
  REGISTRY: ghcr.io

jobs:
  build-docker-and-push:
    runs-on: ubuntu-22.04
    permissions:
      packages: write
      contents: read
    steps:
    - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

    - uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5.0.0
      with:
        images: ${{ env.REGISTRY }}/${{ github.repository }}

    - name: Build and push Docker image
      uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
      with:
        context: .
        file: builders/${{ inputs.name }}/Dockerfile
        push: true
        tags: ${{ env.REGISTRY }}/nordsecurity/${{ inputs.name }}-${{ inputs.rust_version }}:${{ inputs.version }}
