name: Linters
on: [push]
permissions: {}

jobs:
  python-format-black:
    permissions:
      contents: read
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - run: pip3 install -r ./requirements.txt
      - run: black --check --diff --color .
  natlab-typecheck:
    permissions:
      contents: read
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - run: pip3 install -r ./requirements.txt
      - run: mypy .
