name: Test build in docker
on:
  workflow_call:
    inputs:
      arch:
        required: true
        type: string
      target_os:
        required: true
        type: string
permissions: {}

jobs:
  test-build:
    permissions:
      contents: read
      packages: read
    strategy:
      matrix:
        debug: ['--debug', '']
    runs-on: ubuntu-22.04
    container:
      image: ${{ inputs.target_os == 'linux' && 'ghcr.io/nordsecurity/build-linux-rust1.89.0:v6.3.0' || 'ghcr.io/nordsecurity/build-android-rust1.89.0:v6.3.0' }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Build rust sample
        run: python3 rust_sample/ci/build_sample.py build ${{ inputs.target_os }} ${{ inputs.arch }} ${{ matrix.debug }}
      - uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        with:
          name: rust-sample-${{ inputs.target_os }}-${{ inputs.arch }}${{ matrix.debug }}
          path: rust_sample/dist
