name: Test build on native
on:
  workflow_call:
    inputs:
      arch:
        required: true
        type: string
      target_os:
        required: true
        type: string
      runner:
        required: true
        type: string
permissions: {}

jobs:
  test-build:
    permissions:
      contents: read
    strategy:
      matrix:
        debug: ['--debug', '']
    runs-on: ${{ inputs.runner }}
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Build rust sample
        run: python3 rust_sample/ci/build_sample.py build ${{ inputs.target_os }} ${{ inputs.arch }} ${{ matrix.debug }}
      - uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        with:
          name: rust-sample-${{ inputs.target_os }}-${{ inputs.arch }}${{ matrix.debug }}
          path: rust_sample/dist
